name: 🔖 Pre-release

on:
  push:
    tags: ['v*']

jobs:
  pre-release:
    uses: ./.github/workflows/cd-release.yml
    permissions:
      contents: write
    with:
      packages: package.json
      prerelease: true
